### ISSUE TITLE
panic: sync: negative WaitGroup counter during strimzi roll of brokers

### ISSUE THREAD

**Issue by k-wall** [strimzi/strimzi-canary#38]
I noticed the canary die like this during a Strimzi orchestrated roll of the kafka brokers.  Kubernetes restarted the canay, so there was no end user impact.

```
2021/04/13 16:55:11 Consumer group handler consumeclaim
panic: sync: negative WaitGroup counter

goroutine 581 [running]:
sync.(*WaitGroup).Add(0xc0001a01b0, 0xffffffffffffffff)
	/usr/lib/golang/src/sync/waitgroup.go:74 +0x147
sync.(*WaitGroup).Done(...)
	/usr/lib/golang/src/sync/waitgroup.go:99
github.com/strimzi/strimzi-canary/internal/services.(*consumerGroupHandler).ConsumeClaim(0xc00000e0b0, 0xb3eb40, 0xc00042ec00, 0xb39dc0, 0xc0001710b0, 0x10, 0x0)
	/home/ppatiern/github/strimzi-canary/internal/services/consumer.go:194 +0x7f
github.com/Shopify/sarama.(*consumerGroupSession).consume(0xc00042ec00, 0xc000220920, 0x10, 0x0)
	/home/ppatiern/go/pkg/mod/github.com/!shopify/sarama@v1.27.2/consumer_group.go:690 +0x28f
github.com/Shopify/sarama.newConsumerGroupSession.func2(0xc00042ec00, 0xc000220920, 0x10, 0xc000000000)
	/home/ppatiern/go/pkg/mod/github.com/!shopify/sarama@v1.27.2/consumer_group.go:615 +0x87
created by github.com/Shopify/sarama.newConsumerGroupSession
	/home/ppatiern/go/pkg/mod/github.com/!shopify/sarama@v1.27.2/consumer_group.go:607 +0x53b
```

**Comment by ppatierno** [comment]
Thanks to https://github.com/strimzi/strimzi-canary/pull/45 this error cannot happen anymore.
